---
- hosts: lighthouse-master  
  gather_facts: false
  become: true
  become_method: sudo
  roles:
    - vsphere-linux
    - lin_vsphere_domain_join

  # tasks:
  #   - debug: msg="My Secret value is {{lin_docker_lighthouse_bindpw | replace('\n', '')}}"